server:
  port: 8090



mq:
  consumer:
    #消费者总开关 0关 1开
    enabled: 1
  #rebbitmq消费者开关，true开启，false关闭
  rabbitmq:
    consumer:
      enabled: true


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/cmh_project?useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: Chuminghao5176
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # 开启confirms回调 P -> Exchange
    publisher-confirms: true
    # 开启returnedMessage回调 Exchange -> Queue
    publisher-returns: true
    # 设置手动确认(ack) Queue -> C
    istener:
      simple:
        acknowledge-mode: manual
        prefetch: 100

  mail:
    host: smtp.163.com
    username: chuminghao566@163.com
    password: cmh521
    from: chuminghao566@163.com
    properties:
      mail:
        smtp:
          auth: true
          starttls: true
          required: true
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
  application:
    name: eureka-client-service

mybatis:
  #查询返回类型查询地址路径
  type-aliases-package: com.cmh.project.biz.dao.db.entity
  #驼峰命名规则
  configuration:
    map-underscore-to-camel-case: true

eureka:
  instance:
    hostname: client
    instance-id: ${spring.application.name}:${vcap.application.instance_id:&{spring.application.instance_id:${random.value}}}
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/

es:
  clusterName: my-application
  ips: 127.0.0.1:9300

sso:
  exclude: /**/register