server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/cmh_project?useUnicode=true&characterEncoding=utf-8
    username: root
    password:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # 开启confirms回调 P -> Exchange
    publisher-confirms: true
    # 开启returnedMessage回调 Exchange -> Queue
    publisher-returns: true
    # 设置手动确认(ack) Queue -> C
    istener:
      simple:
        acknowledge-mode: manual
        prefetch: 100

  mail:
    host: smtp.163.com
    username: chuminghao566@163.com
    password: cmh521
    from: chuminghao566@163.com
    properties:
      mail:
        smtp:
          auth: true
          starttls: true
          required: true
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
sso:
  exclude: /**/register